
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: juke-final-ep-2026
model: azureml:mlops-demo-model@latest
code_configuration:
  code: .
  scoring_script: score.py
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest
instance_type: Standard_DS2_v2
instance_count: 1
